FROM node:lts

ENV NODE_ENV=production

WORKDIR /usr/src/app

# Install app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install --production --silent

# Copy the rest of the application code
COPY . .

# Expose the port Next.js runs on
EXPOSE 3000

# Start the Next.js application
CMD ["sh", "-c", "npm run build && npm run start"]


